
name: Build and deploy Next.js Insta stuff

on:
  push:
    branches:
      - nextjs
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
      - name: Zip artifact for deployment
        run: zip -r release.zip ./out

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d deploy

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6F709211A91C4018BFB3E04F4AC0329D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D3AF5427B21F4216BF42637B522251BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FD5B0E4D0A6E4F11A45CD74F53C61D8E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'yt1s'
          slot-name: 'Production'
          package: ./deploy
